Move C++ libraries depending on libc++/abi forward
This fixes a runtime error saying:
> dyld: Symbol not found: __ZNKSt11logic_error4whatEv
when running Flint on OS X 10.8, which is built with Xcode 8.1.